In [3]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] = False #用来正常显示负号
import seaborn as sns

from sklearn import linear_model
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import cross_val_score
from sklearn.grid_search import GridSearchCV
from sklearn.linear_model import Lasso,Ridge
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, cross_val_score, KFold,StratifiedKFold

# data
%store -r x
%store -r y


In [11]:
# data
%store -r x
%store -r y

# Number of random trials
NUM_TRIALS = 1
inner_splits=5
outer_splits=5
random_seed=1
jobs=6

# Set up possible values of parameters to optimize over
p_range = (0.001, 0.01, 0.1, 1.0, 10.0)
p_grid = {"C": p_range,
          "gamma": p_range}

# We will use a Support Vector Classifier with "rbf" kernel
svm = SVR(kernel="rbf")



# Arrays to store scores
non_nested_scores = np.zeros(NUM_TRIALS)
nested_scores = np.zeros(NUM_TRIALS)

# Loop for each trial
for i in range(NUM_TRIALS):

    # Choose cross-validation techniques for the inner and outer loops,
    # independently of the dataset.
    # E.g "LabelKFold", "LeaveOneOut", "LeaveOneLabelOut", etc.
    inner_cv = KFold(n_splits=inner_splits, shuffle=True, random_state=random_seed)
    outer_cv = KFold(n_splits=outer_splits, shuffle=True, random_state=random_seed)

    # Non_nested parameter search and scoring
    clf = GridSearchCV(estimator=svm, param_grid=p_grid, scoring='neg_mean_squared_error',cv=inner_cv, n_jobs=jobs)
    clf.fit(x, y)
    non_nested_scores[i] = clf.best_score_

    # Nested CV with parameter optimization
    nested_score = cross_val_score(clf,x, y,scoring='neg_mean_squared_error', cv=outer_cv, n_jobs=jobs)
    nested_scores[i] = nested_score.mean()




In [12]:
nested_scores

array([-0.03189786])

In [13]:
non_nested_scores

array([-0.03137131])

In [4]:
from sklearn.model_selection import LeaveOneOut
# Number of random trials
NUM_TRIALS = 1
inner_splits=500
outer_splits=10
random_seed=1
jobs=6

# Set up possible values of parameters to optimize over
p_range = (0.0001,0.0005,0.001,0.005, 0.01,0.05, 0.1)
p_grid = {"alpha": p_range
         }

# We will use a Support Vector Classifier with "rbf" kernel
lasso = Lasso()


# Arrays to store scores
non_nested_scores = np.zeros(NUM_TRIALS)
nested_scores = np.zeros(NUM_TRIALS)

# Loop for each trial
for i in range(NUM_TRIALS):

    # Choose cross-validation techniques for the inner and outer loops,
    # independently of the dataset.
    # E.g "LabelKFold", "LeaveOneOut", "LeaveOneLabelOut", etc.
    inner_cv = LeaveOneOut()
    outer_cv = KFold(n_splits=outer_splits, shuffle=True, random_state=random_seed)

    # Non_nested parameter search and scoring
    clf = GridSearchCV(estimator=lasso, param_grid=p_grid, scoring='neg_mean_squared_error',cv=inner_cv, n_jobs=jobs)
    clf.fit(x, y)
    non_nested_scores[i] = clf.best_score_

    # Nested CV with parameter optimization
    nested_score = cross_val_score(clf,x, y,scoring='neg_mean_squared_error', cv=outer_cv, n_jobs=jobs)
    nested_scores[i] = nested_score.mean()

In [5]:
nested_scores

array([-0.03420565])

In [6]:
non_nested_scores

array([-0.03108659])

In [7]:
clf.best_params_

{'alpha': 0.001}

In [8]:
clf.best_estimator_

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [18]:
from sklearn.feature_selection import RFECV
from sklearn.svm import SVR

estimator = SVR(kernel="linear")
selector = RFECV(estimator, step=1, cv=LeaveOneOut())
selector = selector.fit(x, y)

print(selector.support_ )
print(n_features_)
selector.ranking_

'raise'

In [13]:
data_num=pd.read_csv(r'C:\Python\kaggle\@ON-工业AI\data\initial_feature_selection\data_num.csv')

In [11]:
null_feature=pd.read_csv(r'C:\Python\kaggle\@ON-工业AI\data\构造特征\data_null_count.csv')

In [35]:
tools= pd.read_csv(r'C:\Python\kaggle\@ON-工业AI\data\raw_data\tools_encode.csv')

In [37]:
tools.drop(['Unnamed: 0','Tool','tool (#1)','TOOL (#1)','TOOL (#2)','Tool (#3)'],inplace=True,axis=1)

In [26]:
null_feature.drop(null_feature.var()[null_feature.var()==0].index,axis=1,inplace=True)

In [34]:
null_feature.iloc[:,1:]

null_count_all  null_count_210X  null_count_220X  null_count_300X  \
0               198                0                2                0   
1               203                0                2                5   
2               198                0                2                0   
3               199                0                2                1   
4               198                0                2                0   
5               200                0                2                0   
6               200                0                2                2   
7                68                0                2                5   
8                63                0                2                0   
9                64                0                2                1   
10               63                0                2                0   
11              198                0                2                0   
12              213                0                2                1   
13              198                0                2                0   
14              198                0                2                0   
15              199                0                2                1   
16              201                0                2                3   
17              198                0                2                0   
18              199                0                2                1   
19              198                0                2                0   
20              198                0                2                0   
21              203                0                2                5   
22              200                0                2                2   
23              200                0                2                2   
24               62                0                2                0   
25               64                0                2                0   
26              199                0                2                1   
27              212                0                2                0   
28              198                0                2                0   
29               62                0                2                0   
..              ...              ...              ...              ...   
691              63                0                2                0   
692              63                0                2                0   
693              63                0                2                0   
694              62                0                2                0   
695              64                0                2                0   
696             204                0                2                5   
697              64                0                2                0   
698              63                0                2                0   
699             201                0                2                2   
700             199                0                2                1   
701              70                0                2                7   
702              63                0                2                0   
703              63                0                2                0   
704            1649                0                2                0   
705            1651                0                2                1   
706            1515                0                2                0   
707             198                0                2                0   
708             198                0                2                0   
709              80                0                2                2   
710              63                0                2                0   
711              62                0                2                0   
712              63                0                2                1   
713      

In [14]:
lisan_all_fillna=lisan_all.apply(lambda x:x.fillna(x.median()))

In [15]:
lisan_all_fillna_999=lisan_all.fillna(-999)

In [44]:
null_feature_c=null_feature.iloc[:,2:].copy()

In [55]:
data=pd.concat((lisan_all_fillna_999,null_feature_c,tools),axis=1)

In [ ]:
data

In [58]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
oh=OneHotEncoder()
for i in data.columns:
    data[i]=le.fit_transform(data[i])

In [65]:
data.dum

312X292  520X314  220X365  261X477  312X379  360X1440  312X382  261X662  \
0          1        3        4        1        4         1        4        2   
1          2        2        2        1        4         1        4        1   
2          1        2        2        2        4         1        4        2   
3          2        2        1        1        3         1        3        1   
4          1        3        3        1        4         1        3        1   
5          1        3        2        1        4         1        4        1   
6          1        2        3        1        4         1        4        2   
7          1        2        3        2        2         1        1        2   
8          1        2        3        1        2         1        1        1   
9          1        2        2        1        2         1        2        1   
10         1        3        2        1        2         1        1        1   
11         1        3        3        1        4         1        4        2   
12         1        2        3        0        4         1        3        1   
13         1        2        3        2        4         1        4        2   
14         1        2        3        2        4         0        4        2   
15         1        2        2        0        4         0        3        1   
16         1        3        2        1        4         0        4        2   
17         1        2        3        1        4         0        4        1   
18         1        2        2        2        4         0        4        2   
19         1        3        2        1        3         0        3        1   
20         1        2        2        1        4         0        4        2   
21         1        2        1        1        4         0        3        1   
22         1        3        3        1        4         0        4        2   
23         1        2        2        1        4         0        3        1   
24         1        2        2        2        1         1        1        2   
25         1        2        2        2        2         1        1        2   
26         1        2        2        1        3         0        3        1   
27         1        2        2        2        4         1        3        2   
28         2        1        2        2        4         1        3        2   
29         1        2        3        2        4         2        4        2   
..       ...      ...      ...      ...      ...       ...      ...      ...   
691        0        1        2        2        2         1        2        2   
692        1        2        2        2        4         1        4        2   
693        1        2        2        0        2         1        1        1   
694        1        2        1        2        2         0        1        3   
695        1        3        3        2        2         0        2        2   
696        2        2        3        1        3         0        3        2   
697        0        2        3        2        1         0        1        2   
698        1        2        2        2        4         0        4        2   
699        2        3        2        1        3         1        3        1   
700        2        2        3        1        4         1        4        1   
701        1        1        2        2        2         2        1        1   
702        1        2        1        2        4         2        3        0   
703        1        2        3        1        4         1        4        1   
704        1        2        3        1        4         0        3        1   
705        2        2        3        0        4         0        3        1   
706        0        2        2        1        0         0        0        1   
707        1        2        3        0        4         1        4        1   
708        1        2        2        1        4         1        4        1   
709  

In [59]:
oh_data=oh.fit_transform(data)

In [64]:
oh_data

<721x6239 sparse matrix of type '<class 'numpy.float64'>'
	with 837802 stored elements in Compressed Sparse Row format>

In [83]:
dum_data

0  1  2  0  1  2  3  0  1  2 ...  3  4  5  6  7  8  0  1  2  3
0    0  1  0  0  0  0  1  0  0  0 ...  0  0  0  0  0  0  0  1  0  0
1    0  0  1  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  0  1  0
2    0  1  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  1  0  0
3    0  0  1  0  0  1  0  0  1  0 ...  0  0  0  0  0  0  0  1  0  0
4    0  1  0  0  0  0  1  0  0  0 ...  0  0  0  0  0  0  0  1  0  0
5    0  1  0  0  0  0  1  0  0  1 ...  0  0  0  0  0  0  0  1  0  0
6    0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  0  1  0
7    0  1  0  0  0  1  0  0  0  0 ...  1  0  0  0  0  0  0  0  1  0
8    0  1  0  0  0  1  0  0  0  0 ...  1  0  0  0  0  0  0  1  0  0
9    0  1  0  0  0  1  0  0  0  1 ...  0  0  0  1  0  0  0  1  0  0
10   0  1  0  0  0  0  1  0  0  1 ...  0  1  0  0  0  0  0  1  0  0
11   0  1  0  0  0  0  1  0  0  0 ...  0  0  0  0  0  0  0  0  1  0
12   0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  1  0  0
13   0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  0  1  0
14   0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  0  1  0
15   0  1  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  1  0  0
16   0  1  0  0  0  0  1  0  0  1 ...  0  0  0  0  0  0  0  0  1  0
17   0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  1  0  0
18   0  1  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  0  1  0
19   0  1  0  0  0  0  1  0  0  1 ...  0  0  0  0  0  0  0  1  0  0
20   0  1  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  0  1  0
21   0  1  0  0  0  1  0  0  1  0 ...  0  0  0  0  0  0  0  1  0  0
22   0  1  0  0  0  0  1  0  0  0 ...  0  0  0  0  0  0  0  0  1  0
23   0  1  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  1  0  0
24   0  1  0  0  0  1  0  0  0  1 ...  1  0  0  0  0  0  0  0  0  1
25   0  1  0  0  0  1  0  0  0  1 ...  0  1  0  0  0  0  0  1  0  0
26   0  1  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  1  0  0
27   0  1  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  0  1  0
28   0  0  1  0  1  0  0  0  0  1 ...  0  0  0  0  0  0  0  1  0  0
29   0  1  0  0  0  1  0  0  0  0 ...  0  0  1  0  0  0  1  0  0  0
..  .. .. .. .. .. .. .. .. .. .. ... .. .. .. .. .. .. .. .. .. ..
691  1  0  0  0  1  0  0  0  0  1 ...  0  0  0  1  0  0  0  0  0  1
692  0  1  0  0  0  1  0  0  0  1 ...  0  0  1  0  0  0  0  1  0  0
693  0  1  0  0  0  1  0  0  0  1 ...  0  1  0  0  0  0  0  0  1  0
694  0  1  0  0  0  1  0  0  1  0 ...  1  0  0  0  0  0  0  1  0  0
695  0  1  0  0  0  0  1  0  0  0 ...  0  0  0  1  0  0  0  0  0  1
696  0  0  1  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  0  1  0
697  1  0  0  0  0  1  0  0  0  0 ...  0  0  0  0  0  1  0  0  1  0
698  0  1  0  0  0  1  0  0  0  1 ...  0  0  1  0  0  0  0  0  0  1
699  0  0  1  0  0  0  1  0  0  1 ...  0  0  0  0  0  0  0  0  1  0
700  0  0  1  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  1
701  0  1  0  0  1  0  0  0  0  1 ...  1  0  0  0  0  0  0  1  0  0
702  0  1  0  0  0  1  0  0  1  0 ...  0  0  1  0  0  0  0  0  1  0
703  0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  1  0  0  0  0  1
704  0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  1  0  0
705  0  0  1  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  1  0  0
706  1  0  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  1  0  0  0  1
707  0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  0  0  0  1  0  0
708  0  1  0  0  0  1  0  0  0  1 ...  0  0  0  0  0  0  0  0  1  0
709  0  1  0  0  0  1  0  0  0  1 ...  0  0  0  1  0  0  0  0  1  0
710  0  1  0  0  0  1  0  0  0  0 ...  1  0  0  0  0  0  0  0  1  0
711  0  1  0  0  0  1  0  0  0  0 ...  0  1  0  0  0  0  0  0  1  0
712  0  1  0  0  0  1  0  0  0  1 ...  0  1  0  0  0  0  0  1  0  0
713  0  1  0  0  0  1  0  0  0  0 ...  0  0  0  1  0  0  0  0  0  1
714  0  1  0  0  0  1  0  0  0  1 ...  1  0  0  0  0  0  0  0  1  0
715  0  1  0  0  0  1  0  0  0  1 ...  0  1  0  0  0  0  0  1  0  0
716  0  1  0  0  0  1  0  0  0  0 ...  0  0  1  0  0  0  0  1  0  0
717  0  1  0  0  0  1  0  0  0  0 ...  0  0  0  0  1  0  0  0

In [82]:
dum_data=pd.DataFrame(index=data.index)
for i in data.columns:
    dum=pd.get_dummies(data[i])
    dum_data=pd.concat([dum_data,dum],axis=1)

In [90]:
train_x=dum_data.iloc[:500,:].values
test_x=dum_data.iloc[500:,:].values

y = pd.read_csv(r'C:\Python\kaggle\@ON-工业AI\data\raw_data\label.csv',header=None)
y=y[1].values


In [94]:
from sklearn.model_selection import LeaveOneOut
# Number of random trials
NUM_TRIALS = 1
inner_splits=500
outer_splits=10
random_seed=1
jobs=6

# Set up possible values of parameters to optimize over
p_range = (0.0001,0.0005,0.001,0.005, 0.01,0.05, 0.1)
p_grid = {"alpha": p_range
         }

# We will use a Support Vector Classifier with "rbf" kernel
lasso = Lasso()


# Arrays to store scores
non_nested_scores = np.zeros(NUM_TRIALS)
nested_scores = np.zeros(NUM_TRIALS)

# Loop for each trial
for i in range(NUM_TRIALS):

    # Choose cross-validation techniques for the inner and outer loops,
    # independently of the dataset.
    # E.g "LabelKFold", "LeaveOneOut", "LeaveOneLabelOut", etc.
    inner_cv = LeaveOneOut()
    outer_cv = KFold(n_splits=outer_splits, shuffle=True, random_state=random_seed)

    # Non_nested parameter search and scoring
    clf = GridSearchCV(estimator=lasso, param_grid=p_grid, scoring='neg_mean_squared_error',cv=inner_cv, n_jobs=jobs)
    clf.fit(train_x, y)
    non_nested_scores[i] = clf.best_score_

    # Nested CV with parameter optimization
    nested_score = cross_val_score(clf,train_x, y,scoring='neg_mean_squared_error', cv=outer_cv, n_jobs=jobs)
    nested_scores[i] = nested_score.mean()

In [95]:
nested_scores

array([-0.03330838])

In [96]:
non_nested_scores

array([-0.03107498])

In [97]:
clf.best_estimator_

Lasso(alpha=0.005, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [98]:
clf.best_params_

{'alpha': 0.005}

In [99]:
clf.grid_scores_

c:\users\yechao\appdata\local\programs\python\python35\lib\site-packages\sklearn\model_selection\_search.py:747: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)


[mean: -0.03940, std: 0.05598, params: {'alpha': 0.0001},
 mean: -0.03230, std: 0.04756, params: {'alpha': 0.0005},
 mean: -0.03146, std: 0.04848, params: {'alpha': 0.001},
 mean: -0.03107, std: 0.04586, params: {'alpha': 0.005},
 mean: -0.03417, std: 0.04812, params: {'alpha': 0.01},
 mean: -0.04047, std: 0.05423, params: {'alpha': 0.05},
 mean: -0.04047, std: 0.05423, params: {'alpha': 0.1}]

In [103]:
clf.score

<bound method BaseSearchCV.score of GridSearchCV(cv=LeaveOneOut(), error_score='raise',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid=True, n_jobs=6,
       param_grid={'alpha': (0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='neg_mean_squared_error', verbose=0)>

In [106]:
clf.cv_results_

{'split309_train_score': array([ -3.89588485e-05,  -7.65266048e-04,  -2.44870852e-03,
         -1.80248895e-02,  -2.86952548e-02,  -4.03870403e-02,
         -4.03870403e-02]),
 'split352_train_score': array([ -3.91182705e-05,  -7.67093686e-04,  -2.44577852e-03,
         -1.80417220e-02,  -2.86669859e-02,  -4.03843848e-02,
         -4.03843848e-02]),
 'split205_train_score': array([ -3.87969192e-05,  -7.67481691e-04,  -2.44985604e-03,
         -1.79621933e-02,  -2.86485167e-02,  -4.03852470e-02,
         -4.03852470e-02]),
 'split87_test_score': array([-0.02626466, -0.02263034, -0.02100869, -0.02796688, -0.04205889,
        -0.02454615, -0.02454615]),
 'split9_train_score': array([ -3.89241437e-05,  -7.63884159e-04,  -2.44935113e-03,
         -1.79647155e-02,  -2.87045843e-02,  -4.03890265e-02,
         -4.03890265e-02]),
 'split429_test_score': array([-0.04340126, -0.00375802, -0.0001638 , -0.00470597, -0.0001054 ,
        -0.00710699, -0.00710699]),
 'split102_train_score': array([ -3

In [109]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'mean_train_score',
 'param_alpha',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split0_train_score',
 'split100_test_score',
 'split100_train_score',
 'split101_test_score',
 'split101_train_score',
 'split102_test_score',
 'split102_train_score',
 'split103_test_score',
 'split103_train_score',
 'split104_test_score',
 'split104_train_score',
 'split105_test_score',
 'split105_train_score',
 'split106_test_score',
 'split106_train_score',
 'split107_test_score',
 'split107_train_score',
 'split108_test_score',
 'split108_train_score',
 'split109_test_score',
 'split109_train_score',
 'split10_test_score',
 'split10_train_score',
 'split110_test_score',
 'split110_train_score',
 'split111_test_score',
 'split111_train_score',
 'split112_test_score',
 'split112_train_score',
 'split113_test_score',
 'split113_train_score',
 'split114_test_score',
 'split114_train_score',
 'split115_test_score',
 'split115_train_score'

In [110]:
cv_results=pd.DataFrame(clf.cv_results_)

In [111]:
cv_results

mean_fit_time  mean_score_time  mean_test_score  mean_train_score  \
0       8.782864         0.023055        -0.039400         -0.000039   
1       4.247589         0.024435        -0.032297         -0.000766   
2       2.105176         0.025089        -0.031462         -0.002443   
3       0.628722         0.029400        -0.031075         -0.017995   
4       0.741298         0.027548        -0.034166         -0.028657   
5       0.312914         0.036290        -0.040470         -0.040308   
6       0.299191         0.036566        -0.040470         -0.040308   

  param_alpha             params  rank_test_score  split0_test_score  \
0      0.0001  {'alpha': 0.0001}                5          -0.006382   
1      0.0005  {'alpha': 0.0005}                3          -0.006162   
2       0.001   {'alpha': 0.001}                2          -0.008643   
3       0.005   {'alpha': 0.005}                1          -0.001413   
4        0.01    {'alpha': 0.01}                4          -0.000341   
5        0.05    {'alpha': 0.05}                6          -0.009819   
6         0.1     {'alpha': 0.1}                6          -0.009819   

   split0_train_score  split100_test_score       ...         \
0           -0.000039            -0.001278       ...          
1           -0.000767            -0.000015       ...          
2           -0.002453            -0.000359       ...          
3           -0.018018            -0.015793       ...          
4           -0.028713            -0.027935       ...          
5           -0.040369            -0.013859       ...          
6           -0.040369            -0.013859       ...          

   split98_test_score  split98_train_score  split99_test_score  \
0           -0.172797            -0.000037           -0.071596   
1           -0.105396            -0.000749           -0.063400   
2           -0.093091            -0.002408           -0.040278   
3           -0.027486            -0.018009           -0.038930   
4           -0.030004            -0.028584           -0.080189   
5           -0.023306            -0.040342           -0.159132   
6           -0.023306            -0.040342           -0.159132   

   split99_train_score  split9_test_score  split9_train_score  std_fit_time  \
0            -0.000039          -0.019748           -0.000039      0.369106   
1            -0.000758          -0.000303           -0.000764      0.583781   
2            -0.002425          -0.002192           -0.002449      0.516491   
3            -0.018033          -0.012655           -0.017965      0.122308   
4            -0.028638          -0.001691           -0.028705      0.121591   
5            -0.040071          -0.000026           -0.040389      0.103498   
6            -0.040071          -0.000026           -0.040389      0.081911   

   std_score_time  std_test_score  std_train_score  
0        0.015574        0.055982     4.323553e-07  
1        0.015724        0.047559     5.234663e-06  
2        0.014658        0.048479     1.423794e-05  
3        0.018789        0.045856     6.562643e-05  
4        0.017309        0.048121     9.109736e-05  
5        0.026891        0.054228     1.084560e-04  
6        0.026569        0.054228     1.084560e-04  

[7 rows x 1011 columns]

In [108]:
clf.scorer_

make_scorer(mean_squared_error, greater_is_better=False)

In [115]:
submit

array([ 2.75097661,  2.78532177,  2.89702277,  2.98184372,  2.77203097,
        2.88327796,  2.88789501,  2.91337464,  2.80506849,  2.77507625,
        2.79921688,  2.99796996,  2.90622144,  2.81898398,  2.91367517,
        2.87019323,  2.83841093,  2.88107568,  2.73981513,  2.86150515,
        2.96348998,  2.65871838,  2.8593615 ,  2.79847251,  2.78662009,
        2.92730609,  2.81562844,  2.85936829,  2.7959724 ,  2.86340475,
        2.85223565,  2.89432774,  2.88048114,  2.80643741,  2.96678949,
        2.95949999,  2.94204905,  2.93730429,  2.81260082,  2.84095651,
        2.76355597,  2.88663062,  2.8168253 ,  2.93229554,  2.89262946,
        2.92457193,  2.96033477,  2.83071847,  2.82388661,  2.85327405,
        2.84669963,  2.77663976,  2.92638692,  2.86267663,  2.83114937,
        2.90584513,  2.89997871,  2.6837897 ,  2.773928  ,  2.8311772 ,
        2.74588477,  2.71588549,  2.72767622,  2.87071585,  2.91967437,
        2.76005055,  2.80762099,  2.89484341,  2.99513809,  2.71

In [122]:
ceshia=pd.read_excel(r'C:\Python\kaggle\@ON-工业AI\data\测试A.xlsx')
ceshib=pd.read_excel(r'C:\Python\kaggle\@ON-工业AI\data\测试B.xlsx')
ceshi_index=pd.concat([ceshia['ID'],ceshib['ID']],axis=0)

In [125]:
ceshi_index.values

array(['ID716', 'ID717', 'ID719', 'ID720', 'ID721', 'ID722', 'ID723',
       'ID724', 'ID725', 'ID727', 'ID728', 'ID729', 'ID730', 'ID731',
       'ID732', 'ID733', 'ID734', 'ID735', 'ID736', 'ID737', 'ID738',
       'ID739', 'ID740', 'ID741', 'ID742', 'ID743', 'ID744', 'ID745',
       'ID746', 'ID747', 'ID749', 'ID751', 'ID752', 'ID753', 'ID757',
       'ID759', 'ID760', 'ID761', 'ID762', 'ID763', 'ID764', 'ID765',
       'ID766', 'ID768', 'ID769', 'ID770', 'ID771', 'ID772', 'ID773',
       'ID774', 'ID776', 'ID777', 'ID778', 'ID779', 'ID781', 'ID783',
       'ID785', 'ID786', 'ID787', 'ID788', 'ID790', 'ID792', 'ID793',
       'ID797', 'ID798', 'ID801', 'ID802', 'ID803', 'ID804', 'ID806',
       'ID807', 'ID811', 'ID812', 'ID813', 'ID816', 'ID817', 'ID818',
       'ID819', 'ID820', 'ID821', 'ID822', 'ID823', 'ID824', 'ID825',
       'ID826', 'ID833', 'ID834', 'ID835', 'ID838', 'ID839', 'ID841',
       'ID844', 'ID848', 'ID849', 'ID850', 'ID851', 'ID852', 'ID853',
       'ID854', 'ID8

In [137]:
sub=pd.DataFrame(submit,index=ceshi_index.values)
sub[:100].to_csv(r'C:\Python\kaggle\@ON-工业AI\data\sub\20180101.csv',header=None)

In [138]:
sub[:100]

0
ID716  2.750977
ID717  2.785322
ID719  2.897023
ID720  2.981844
ID721  2.772031
ID722  2.883278
ID723  2.887895
ID724  2.913375
ID725  2.805068
ID727  2.775076
ID728  2.799217
ID729  2.997970
ID730  2.906221
ID731  2.818984
ID732  2.913675
ID733  2.870193
ID734  2.838411
ID735  2.881076
ID736  2.739815
ID737  2.861505
ID738  2.963490
ID739  2.658718
ID740  2.859361
ID741  2.798473
ID742  2.786620
ID743  2.927306
ID744  2.815628
ID745  2.859368
ID746  2.795972
ID747  2.863405
...         ...
ID807  2.886176
ID811  2.797100
ID812  2.749316
ID813  2.951134
ID816  2.822407
ID817  2.843293
ID818  2.829945
ID819  2.770944
ID820  2.783333
ID821  2.942148
ID822  2.900258
ID823  2.903249
ID824  2.931202
ID825  2.808226
ID826  2.834716
ID833  2.870739
ID834  2.776525
ID835  2.749949
ID838  2.910420
ID839  2.859362
ID841  2.920034
ID844  2.930048
ID848  2.783108
ID849  2.823943
ID850  2.893143
ID851  2.750526
ID852  2.891849
ID853  2.777978
ID854  3.109419
ID855  2.945310

[100 rows x 1 columns]

In [134]:
from sklearn.model_selection import LeaveOneOut

# Number of random trials
NUM_TRIALS = 1
inner_splits=500
outer_splits=10
random_seed=1
jobs=-1

# Set up possible values of parameters to optimize over
p_range = (0.0001,0.001,0.01,0.1,1)
p_grid = {"alpha": p_range
         }

# We will use a Support Vector Classifier with "rbf" kernel
ridge = Ridge()


# Arrays to store scores
non_nested_scores = np.zeros(NUM_TRIALS)
nested_scores = np.zeros(NUM_TRIALS)

# Loop for each trial
for i in range(NUM_TRIALS):

    # Choose cross-validation techniques for the inner and outer loops,
    # independently of the dataset.
    # E.g "LabelKFold", "LeaveOneOut", "LeaveOneLabelOut", etc.
    inner_cv = LeaveOneOut()
    outer_cv = KFold(n_splits=outer_splits, shuffle=True, random_state=random_seed)

    # Non_nested parameter search and scoring
    clf2 = GridSearchCV(estimator=ridge, param_grid=p_grid, scoring='neg_mean_squared_error',cv=inner_cv, n_jobs=jobs)
    clf2.fit(train_x, y)
    non_nested_scores[i] = clf2.best_score_
    # Nested CV with parameter optimization
    nested_score = cross_val_score(clf2,train_x, y,scoring='neg_mean_squared_error', cv=outer_cv, n_jobs=jobs)
    nested_scores[i] = nested_score.mean()

In [135]:
nested_scores

array([-0.03586083])

In [136]:
clf2.grid_scores_

c:\users\yechao\appdata\local\programs\python\python35\lib\site-packages\sklearn\model_selection\_search.py:747: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)


[mean: -0.03749, std: 0.05767, params: {'alpha': 0.0001},
 mean: -0.03749, std: 0.05767, params: {'alpha': 0.001},
 mean: -0.03749, std: 0.05767, params: {'alpha': 0.01},
 mean: -0.03748, std: 0.05765, params: {'alpha': 0.1},
 mean: -0.03737, std: 0.05747, params: {'alpha': 1}]